security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    encoders:
        App\Entity\Usuario: 
            algorithm: bcrypt
            cost: 12
        Symfony\Component\Security\Core\User\User: bcrypt    
        
    providers:
        chain_provider:
            chain:
                providers: [ in_memory, usuario_provider ]
        in_memory:
            memory:
                users:
                    admin: { password: $2y$13$jwgdL7Y7fXWfbWzYqVvSceUgVc81mluNgrykl2HC6JlTO4AjblhLi , roles: 'ROLE_SUPER_ADMIN'}    
        usuario_provider:
            entity: 
                class: App\Entity\Usuario
                property: apodo
                
    firewalls:
        secured_area:
            pattern: ^/admin
            provider: in_memory
            http_basic:
                realm: "Secured Area"
                provider: in_memory
            logout:
                path:   /logout
                target: /    
                invalidate_session: true
                delete_cookies:
                    REMEMBERME: { path: null, domain: null}
        main:
            anonymous: ~
            pattern: ^/
            http_basic: ~
            provider: usuario_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: index
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /login
                invalidate_session: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false 
            
    access_control:
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: ROLE_USER }
        - { path:  ^/crear-receta, roles: ROLE_USER }
        - { path:  ^/admin, roles: ROLE_ADMIN }
