index:
    path: /
    controller: App\Controller\IndexController::index

perfil:
    path: perfil
    controller: App\Controller\UsuarioController::perfilUsuario
    
mostrar_categoria:
    path: /recetas/{nombre}
    controller:  App\Controller\RecetaController:listadoRecetas
    
menu:
    path: /recetas/{nombre}
    controller:  App\Controller\CategoriaController:menuCategorias