index:
    path: /
    controller: App\Controller\IndexController::index

perfil:
    path: /perfil/{apodo}
    controller: App\Controller\UsuarioController::perfilUsuario
    
mostrar_categoria:
    path: /recetas/{nombre}
    controller:  App\Controller\RecetaController:listadoRecetas
    
menu:
    path: /recetas/{nombre}
    controller:  App\Controller\CategoriaController:menuCategorias
    
crear-receta:
    path: /crear-receta/
    controller: App\Controller\RecetaController:crearReceta

    
#Admin routes#    
perfil-admin:
    path: /admin/perfil/{user}
    controller: App\Controller\UsuarioController::perfilUsuario

