index:
    path: /
    controller: App\Controller\IndexController::index

perfil:
    path: /{_locale}/perfil/{apodo}
    controller: App\Controller\UsuarioController::perfilUsuario
    requirements:
        _locale: es|en
    
registro:
    path: /{_locale}/registro
    controller: App\Controller\RegistrationController:registration
    requirements:
        _locale: es|en


mostrar_categoria:
    path: /{_locale}/{nombre}
    controller:  App\Controller\RecetaController:listadoRecetas
    requirements:
        _locale: es|en   

menu:
    path: /{_locale}/{nombre}
    controller:  App\Controller\CategoriaController:menuCategorias
    requirements:
        _locale: es|en

crear-receta:
    path: /{_locale}/crear-receta/
    controller: App\Controller\RecetaController:crearReceta
    requirements:
        _locale: es|en

mostrar_receta:
    path: /{_locale}/{nombre}/{slug}
    controller:  App\Controller\RecetaController:mostrarRecetas
    requirements:
        _locale: es|en  
    
#Admin routes#    
perfil-admin:
    path: /admin/perfil/{user}
    controller: App\Controller\UsuarioController::perfilUsuario

